Refactor reason to artifact for generic

diff --git a/.github/workflows/bwwl_operations.yml b/.github/workflows/bwwl_operations.yml
--- a/.github/workflows/bwwl_operations.yml
+++ b/.github/workflows/bwwl_operations.yml
@@ -11,8 +11,8 @@ on:
         description: "Single action to add. ex: actions/checkout"
         required: false
         type: string
-      reason:
-        description: "Business reason for the new action."
+      artifact:
+        description: "Artifact reference (JIRA ticket, business reason, etc) for the new action."
         required: false
         type: string
   schedule:
@@ -28,15 +28,15 @@ jobs:
       pull-requests: write
     env:
       _ACTION: ${{ inputs.action }}
-      _REASON: ${{ inputs.reason }}
+      _ARTIFACT: ${{ inputs.artifact }}
     steps:
       - name: Check for action input
         if: ${{ inputs.operation == 'add' && !env._ACTION }}
         run: echo "Action input is required for operation 'add'" && exit 1
 
-      - name: Check for business reason
-        if: ${{ inputs.operation == 'add' && !env._REASON }}
-        run: echo "Business reason is required for operation 'add'" && exit 1
+      - name: Check for artifact reference
+        if: ${{ inputs.operation == 'add' && !env._ARTIFACT }}
+        run: echo "Artifact reference is required for operation 'add'" && exit 1
 
       - name: Log in to Azure
         uses: bitwarden/gh-actions/azure-login@main
@@ -143,7 +143,7 @@ jobs:
         env:
           GH_TOKEN: ${{ steps.app-token.outputs.token }}
           TITLE: "Update/Add bwwl approved actions${{ inputs.operation == 'add' && env._ACTION != '' && format(' for {0}', env._ACTION) || '' }}"
-          REASON: "${{ inputs.operation == 'add' && format('\n    ## Business Reason\n    {0}\n', env._REASON) || '' }}"
+          ARTIFACT: "${{ inputs.operation == 'add' && format('\n    ## Artifact Reference\n    {0}\n', env._ARTIFACT) || '' }}"
         run: |
           PR_URL=$(gh pr create --title "$TITLE" \
             --base "main" \
@@ -160,7 +160,7 @@ jobs:
 
               ## Initiated by
               ${{ github.actor }}
-              $REASON
+              $ARTIFACT
               ## Description
               - This PR updates the approved actions for the Bitwarden Workflow Linter.")
           echo "pr_number=${PR_URL##*/}" >> $GITHUB_OUTPUT
