[BRE-1296] Failing on files that do not exist (#180)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,11 +4,12 @@ on:
   pull_request:
   workflow_dispatch:
 
-permissions: read-all
+permissions:
+  contents: read
 
 jobs:
-  test:
-    name: CI workflow-linter (v2)
+  test-unit:
+    name: Unit Tests
     strategy:
       fail-fast: false
       matrix:
@@ -43,8 +44,31 @@ jobs:
         if: startsWith(matrix.os, 'ubuntu')
         run: pipenv run pytype src
 
-      - name: Install local bwwl binary
-        run: pipenv run pip install -e .
+  test-integration:
+    name: Integration Tests
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - os: ubuntu-24.04
+          - os: windows-2022
+    runs-on: ${{ matrix.os }}
+    defaults:
+      run:
+        shell: bash
+    steps:
+      - name: Check out repo
+        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
+        with:
+          persist-credentials: false
+
+      - name: Set up Python
+        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
+        with:
+          python-version-file: ".python-version"
+
+      - name: Install bwwl binary
+        run: python -m pip install --upgrade .
 
       - name: Test against example workflows
         # run notes:
@@ -54,16 +78,54 @@ jobs:
         #   settings.yaml, which better simulates running from another repository
         # - Using strict to ensure that our examples pass all checks including warnings
         working-directory: .github/workflows
-        run: pipenv run bwwl lint --strict -f ./examples
+        env:
+          files: "examples/ examples/example.yaml"
+        run: |
+          echo "$files"
+          bwwl lint --strict -f $files
+
+      - name: Lint - Non-existent file
+        id: non-existent-file
+
+        env:
+          files: ".github/workflows/---does-not-exist.yml"
+        run: |
+          echo "$files"
+          bwwl lint -f $files
+        continue-on-error: true
+
+      - name: Lint - Invalid file
+        id: invalid-file
+
+        env:
+          files: "tests/fixtures/test_workflow_incorrect.yaml"
+        run: |
+          echo "$files"
+          bwwl lint -f $files
+        continue-on-error: true
+
+      - name: Verify failures are detected
+        env:
+          OUTCOME_NON_EXISTENT_FILE: ${{ steps.non-existent-file.outcome }}
+          OUTCOME_INVALID_FILE: ${{ steps.invalid-file.outcome }}
+        run: |
+          if [ "$OUTCOME_NON_EXISTENT_FILE" != "failure" ]; then
+            echo "Linting did not correctly fail on non-existent file."
+            exit 1
+          fi
+          if [ "$OUTCOME_INVALID_FILE" != "failure" ]; then
+            echo "Linting did not correctly fail on invalid file."
+            exit 1
+          fi
 
       - name: Test bwwl actions - add
         env:
           _ACTION: bitwarden/gh-actions
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Avoid rate limiting
-        run: pipenv run bwwl actions add -o src/bitwarden_workflow_linter/default_actions.json "$_ACTION"
+        run: bwwl actions add -o src/bitwarden_workflow_linter/default_actions.json "$_ACTION"
 
       # TODO: Add this test back in and added related error logging to fix the underlying issue
       # - name: Test bwwl actions - update
       #   env:
       #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Avoid rate limiting
-      #   run: pipenv run bwwl actions update -o src/bitwarden_workflow_linter/default_actions.json
+      #   run: bwwl actions update -o src/bitwarden_workflow_linter/default_actions.json
