[BRE-53] Publish workflow fixes (#5)
* Fix version type workflow

* Fix cd input

* Add run name for cd

* Add enforce version label

* Stub version

* FIx

* Comment out for testing

* Fix

* Bump version from 0.0.3 to 0.0.4

* Testing

* Remove testing changes

* Remove ifs

* Revert "Bump version from 0.0.3 to 0.0.4"

This reverts commit dea8b727be5b9893ea8d166282b0754ab9ff6dfc.

* Fix condition for version label

* Change ! to == false

* Echo labels

* Maybe fix

* Remove echo

---------

Co-authored-by: bitwarden-devops-bot <106330231+bitwarden-devops-bot@users.noreply.github.com>

diff --git a/.github/workflows/enforce-labels.yml b/.github/workflows/enforce-labels.yml
--- a/.github/workflows/enforce-labels.yml
+++ b/.github/workflows/enforce-labels.yml
@@ -7,3 +7,15 @@ on:
 jobs:
   enforce-labels:
     uses: bitwarden/gh-actions/.github/workflows/_enforce-labels.yml@main
+
+  enforce-version-label:
+    if: "!(contains(github.event.pull_request.labels.*.name, 'version:major') || contains(github.event.pull_request.labels.*.name, 'version:minor') || contains(github.event.pull_request.labels.*.name, 'version:patch'))"
+    name: Enforce version label
+    runs-on: ubuntu-22.04
+
+    steps:
+      - name: Check for label
+        run: |
+          echo "PR without the version label cannot be merged."
+          echo "### :x: PR without the version label cannot be merged" >> $GITHUB_STEP_SUMMARY
+          exit 1
